import pathlib
import pygame

# colors
WHITE = pygame.color.Color('#ffffff')
LIGHT_YELOW = pygame.color.Color('#ffffe0')
PURPLE = pygame.color.Color('#6967d1')
LIGHT_BLUE = pygame.color.Color('#6791d1')
INDIGO = pygame.color.Color('#67abd1')
LIGHT_BROWN = pygame.color.Color('#857473')
GREY = pygame.color.Color('#a0a0a0')

SCREEN_COLOR = LIGHT_YELOW

START_IMAGE_PATH = pathlib.Path('images/Start Desk.png')
START_IMAGE_COORDS = (245, 15)

BUTTON_DEFAULT_HITBOX = pygame.Rect(242, 440, 400, 90)
BUTTON_DEFAULT_TEXT_COLOR = WHITE
BUTTON_DEFAULT_CONTENT = 'NO TEKST'
BUTTON_DEFAULT_FONT_FAMILY = 'arial'
BUTTON_DEFAULT_FONT_SIZE = 24
BUTTON_DEFAULT_FONT_STYLE_NORMAL = 0
BUTTON_DEFAULT_FONT_STYLE_BOLD = 0b001
BUTTON_DEFAULT_FONT_STYLE_ITALIC = 0b010
BUTTON_DEFAULT_FONT_STYLE_UNDERSCORE = 0b100

BUTTON_DEFAULT_DEFAULT_TEXTURE = PURPLE
BUTTON_DEFAULT_HOVER_TEXTURE = LIGHT_BLUE
BUTTON_DEFAULT_CLICK_TEXTURE = INDIGO
BUTTON_DEFAULT_BOARDER_RADIUS = 24

BUTTON_THREE_HITBOX = pygame.Rect(242, 400, 400, 90)
BUTTON_THREE_CONTENT = '3 × 3'

BUTTON_FOUR_HITBOX = pygame.Rect(242, 380, 400, 90)
BUTTON_FOUR_CONTENT = '4 × 4'

BUTTON_GENERATE_HITBOX = pygame.Rect(242, 770, 400, 90)
BUTTON_GENERATE_CONTENT = 'Generate'
BUTTON_GENERATE_DEFAULT_TEXTURE = PURPLE
BUTTON_GENERATE_HOVER_TEXTURE = LIGHT_BLUE
BUTTON_GENERATE_CLICK_TEXTURE =INDIGO
BUTTON_GENERATE_BOARDER_RADIUS = 32

BUTTON_BACK_HITBOX = pygame.Rect(65, 474, 190, 90)
BUTTON_BACK_CONTENT = 'Back'
BUTTON_BACK_DEFAULT_TEXTURE = PURPLE
BUTTON_BACK_HOVER_TEXTURE = LIGHT_BLUE
BUTTON_BACK_CLICK_TEXTURE = INDIGO
BUTTON_BACK_BOARDER_RADIUS = 32

BUTTON_RESET_HITBOX = pygame.Rect(235, 474, 190, 90)
BUTTON_RESET_CONTENT = 'Reset'
BUTTON_RESET_DEFAULT_TEXTURE = PURPLE
BUTTON_RESET_HOVER_TEXTURE = LIGHT_BLUE
BUTTON_RESET_CLICK_TEXTURE = INDIGO
BUTTON_RESET_BOARDER_RADIUS = 32

BUTTON_UNDO_HITBOX = pygame.Rect(405, 474, 190, 90)
BUTTON_UNDO_CONTENT = 'Undo'
BUTTON_UNDO_DEFAULT_TEXTURE = PURPLE
BUTTON_UNDO_HOVER_TEXTURE = LIGHT_BLUE
BUTTON_UNDO_CLICK_TEXTURE = INDIGO
BUTTON_UNDO_BOARDER_RADIUS = 32

START_GROUP_OF_BUTTONS_HITBOX = pygame.Rect(242, 438, 400, 230)
START_GROUP_OF_BUTTONS_MARGINS = (30, 30)

GAME_GROUP_OF_BUTTONS_HITBOX = pygame.Rect(26, 765, 700, 90)
GAME_GROUP_OF_BUTTONS_MARGINS = (64, 64)

NUMBERFIELD_FOR_SIZE_HITBOX = pygame.Rect(242, 665, 200, 90)
NUMBERFIELD_FOR_SIZE_CONTENT = 'size'
NUMBERFIELD_FOR_SIZE_COLOR = pygame.color.Color(105, 103, 209)
NUMBERFIELD_FOR_SIZE_FONT_FAMILY = 'arial'
NUMBERFIELD_FOR_SIZE_FONT_STYLE = 'bold'
NUMBERFIELD_FOR_SIZE_FONT_SIZE = 70

NUMBERFIELD_FOR_WIN_HITBOX = pygame.Rect(242, 665, 200, 90)
NUMBERFIELD_FOR_WIN_CONTENT = 'win'
NUMBERFIELD_FOR_WIN_COLOR = PURPLE
NUMBERFIELD_FOR_WIN_FONT_SIZE = 70
NUMBERFIELD_FOR_WIN_FONT_FAMILY = 'arial'

SIZE_BLOCK_HITBOX = pygame.Rect(242, 665, 200, 90)
WIN_BLOCK_HITBOX = pygame.Rect(442, 665, 200, 90)

ZEROS_TEXTURE = pathlib.Path('images/Frame 4.png')
CROSSES_TEXTURE = pathlib.Path('images/Union.png')
INNER_BOARDERS_COLOR = LIGHT_BROWN

DEPTH = 6
TITLE = 'Tic-Tac-Toe'